### ISSUE TITLE
hey nice script , no issue , just a little bug 

### ISSUE THREAD

**Issue by Maureks** [Boom1053/qb-gruppesechs#1]
hey , i've installed the script and everything works like a charm ! 

the only thing i've come uppon, is the fact when you are holding a bag , and are moving to the truck to load it , when passing the doors it bugs the player , you can only open the door on the 4th or 5th attempt . 

just that , everything else is amazing ! 
thanks , and sorry for the bad english !

**Comment by Boom1053** [comment]
That's not a bug use first person to walk out the doors

**Comment by chunce01** [comment]
> hey , i've installed the script and everything works like a charm !
> 
> the only thing i've come uppon, is the fact when you are holding a bag , and are moving to the truck to load it , when passing the doors it bugs the player , you can only open the door on the 4th or 5th attempt .
> 
> just that , everything else is amazing ! thanks , and sorry for the bad english !

You can resolve this by commenting out the garbage walk animation, this way you are still holding the bag but not shaking which causes what you are seeing.

**Comment by Maureks** [comment]
> > hey , i've installed the script and everything works like a charm !
> > the only thing i've come uppon, is the fact when you are holding a bag , and are moving to the truck to load it , when passing the doors it bugs the player , you can only open the door on the 4th or 5th attempt .
> > just that , everything else is amazing ! thanks , and sorry for the bad english !
> 
> You can resolve this by commenting out the garbage walk animation, this way you are still holding the bag but not shaking which causes what you are seeing.

Thanks ! I'm going to give it a try! 
Much appreciated !


EDIT : 

Thanks chunce01 it really worked! 
Once again , much appreciated ! Happy holidays!

**Comment by Boom1053** [comment]
Fixed <3
