### ISSUE TITLE
hey once again , no problem , just a minor improv

### ISSUE THREAD

**Issue by Maureks** [Boom1053/qb-gruppesechs#2]
Hey , I just added this lines to the qb-target function : 

    ["GruppeSechsPed"] = {
        model = 's_m_m_armoured_02', 
        coords = vector4(-4.04, -659.41, 33.48, 186.04),
        minusOne = true, 
        freeze = true, 
        invincible = true, 
        blockevents = true,
        target = { 
            options = {
                {
                    type = "client",
                    event = "gruppesechs:getTruck",
                    icon = "fas fa-sign-in-alt",
                    label = "Get Gruppe Sechs Truck",
		    job = "gruppesechs",
                },
                {
                    type = "server",
                    event = "gruppesechs:server:PayShift",
                    icon = "fas fa-sign-in-alt",
                    label = "Collect Pay Check",
		    job = "gruppesechs",					
                },
            },
            distance = 1.5,
        },

Just to close it for the Gruppesechs job only. (For those who added it to the City Hall!)
Once again thanks for the script it's really awesome!

P.S- I don't know it it's correct , it worked for me , please correct me if i'am wrong in anyway! Thanks for the attention

**Comment by Boom1053** [comment]
appreciate you <3 it works just fine ive also updated to readme <3
