### ISSUE TITLE
qb target errors 

### ISSUE THREAD

**Issue by fivemNoobDev** [Boom1053/qb-gruppesechs#5]
![Screenshot 2023-12-19 123939](https://github.com/Boom1053/qb-gruppesechs/assets/153878827/b30126a8-138f-4c7b-800a-2db1eeda674b)

**Comment by fivemNoobDev** [comment]
gave errors for alot of scripts but the qb target is the issue

**Comment by fivemNoobDev** [comment]
![image](https://github.com/Boom1053/qb-gruppesechs/assets/153878827/922edf23-edc8-4428-b853-12ec52246a57)

**Comment by Boom1053** [comment]
2 years ago....... go use ox_target.....

**Comment by fivemNoobDev** [comment]
i fixed it i forgot a "}"
